### ISSUE TITLE
Does not run under Ubuntu-MATE 18.04 LTS

### ISSUE THREAD

**Issue by tony-travis** [cropgeeks/topali-v2#1]
Downloaded TOPALi Linux installer on 2018-10-25
32-bit libXtst.so.6 is missing from Ubuntu-MATE 18.04 LTS:

```testing JVM in /opt/TOPALi/jre ...
java.lang.UnsatisfiedLinkError: /opt/TOPALi/jre/lib/i386/xawt/libmawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at sun.security.action.LoadLibraryAction.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.NativeLibLoader.loadLibraries(Unknown Source)
	at sun.awt.DebugHelper.<clinit>(Unknown Source)
	at java.awt.Component.<clinit>(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
java.lang.NoClassDefFoundError: java.awt.Container
	at com.exe4j.runtime.LauncherEngine.handleFailure(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Exception in thread "main" java.lang.NoClassDefFoundError: java.awt.Container
	at com.exe4j.runtime.LauncherEngine.handleFailure(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)

which -a topali
/usr/local/bin/topali

apt-file search libXtst.so.6
libxtst6: /usr/lib/x86_64-linux-gnu/libXtst.so.6
libxtst6: /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0

apt list '*libxtst6*'
Listing... Done
libxtst6/bionic,now 2:1.2.3-1 amd64 [installed]
```

**Comment by imilne** [comment]
Hey, Tony. 32bit Java on 64bit is never nice (assuming that's what you're trying; see https://stackoverflow.com/questions/9393670/how-to-run-a-32bit-jvm-on-a-64bit-linux for instance). If I have time, I'll try to make a proper 64bit installer for TOPALi, but you'd be as good nicking the lib subfolder from a working install (even a Windows one) and simply running: java -jar topali.jar
